export * from './MoviePage'
export * from './MainPage'
export * from './GenresPage'
export * from './MovieDetailsPage'
export * from './SearchPage'
export * from './TVShows'
export * from './Home'
export * from './Player'